name: CMake

on:
  push:
    branches: [ "ghactions" ]
  pull_request:
    branches: [ "ghactions" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  wxBUILD_SHARED: OFF
  wxBUILD_USE_STATIC_RUNTIME: ON 

jobs:
  build-win-msvc:
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install build tools
      run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.WinXP Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP" --version=16.7.7.0
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -A Win32 -T v141_xp -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}} -DwxBUILD_USE_STATIC_RUNTIME=${{env.wxBUILD_USE_STATIC_RUNTIME}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)
      
      
    - uses: actions/upload-artifact@v3
      with:
        name: windows_bin_x86_64
        path: ${{github.workspace}}/build/app/Release/DeltaPatcher.exe
        
