name: CMake

on:
  push:
    branches: [ "ghactions" ]
  pull_request:
    branches: [ "ghactions" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  wxBUILD_SHARED: OFF
  wxBUILD_USE_STATIC_RUNTIME: ON 

jobs:
  build-ubuntu:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Pull dependencies
      run: sudo apt install -y build-essential cmake git libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)
      
      
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: ${{github.workspace}}/build/app/DeltaPatcher
      
  build-win:
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}}       -DwxBUILD_USE_STATIC_RUNTIME=${{env.wxBUILD_USE_STATIC_RUNTIME}} 


    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)
      
      
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: ${{github.workspace}}/build/app/Release/DeltaPatcher.exe      
